### ISSUE TITLE
Efficient EVM verification

### ISSUE THREAD

**Issue by dvc94ch** [ZcashFoundation/frost#319]
I'm trying to modify frost based on [0] to allow efficient signature verification in evm smart contracts using ecrecover (here is the verification code for a schnorr signature [1]). This requires the R in the signature to not be a projective point, but the hash of the projective point. Bellow I attached the work in progress changes to change the challenge format and to take `address(R)` for signature verification.

- [0] https://blog.chain.link/threshold-signatures-in-chainlink/
- [1] https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.5/dev/SchnorrSECP256K1.sol

```diff
diff --git a/frost-core/src/lib.rs b/frost-core/src/lib.rs
index a1cbed7..3d99fc5 100644
--- a/frost-core/src/lib.rs
+++ b/frost-core/src/lib.rs
@@ -229,9 +229,19 @@ pub trait Ciphersuite: Copy + Clone + PartialEq + Debug {
         signature: &Signature<Self>,
         public_key: &VerifyingKey<Self>,
     ) -> Result<(), Error<Self>> {
-        let c = crate::challenge::<Self>(&signature.R, &public_key.element, msg);
+        let c = Self::challenge(&signature.R, &public_key.element, msg);

-        public_key.verify_prehashed(c, signature)
+        public_key.verify_prehashed(Challenge(c), signature)
+    }
+
+    /// Returns the address of an element.
+    fn transform_r(R: Element<Self>) -> Element<Self> {
+        R
+    }
+
+    /// Computes the challenge.
+    fn challenge(R: &Element<Self>, verifying_key: &Element<Self>, msg: &[u8]) -> Scalar<Self> {
+        crate::challenge::<Self>(R, verifying_key, msg).0
     }
 }

diff --git a/frost-core/src/signing_key.rs b/frost-core/src/signing_key.rs
index 36226f1..8eeaaf6 100644
--- a/frost-core/src/signing_key.rs
+++ b/frost-core/src/signing_key.rs
@@ -43,6 +43,7 @@ where
         let k = random_nonzero::<C, R>(&mut rng);

         let R = <C::Group>::generator() * k;
+        let R = C::transform_r(R);

         // Generate Schnorr challenge
         let c = crate::challenge::<C>(&R, &VerifyingKey::<C>::from(*self).element, msg);
diff --git a/frost-secp256k1/Cargo.toml b/frost-secp256k1/Cargo.toml
index a039872..d8ca578 100644
--- a/frost-secp256k1/Cargo.toml
+++ b/frost-secp256k1/Cargo.toml
@@ -24,7 +24,7 @@ features = ["nightly"]
 frost-core = { path = "../frost-core", version = "0.2.0", features = ["test-impl"] }
 k256 = { version = "0.13.0", features = ["arithmetic", "expose-field", "hash2curve"] }
 rand_core = "0.6"
-sha2 = "0.10.2"
+sha3 = "0.10.7"

 [dev-dependencies]
 bincode = "1"
diff --git a/frost-secp256k1/src/lib.rs b/frost-secp256k1/src/lib.rs
index 94932dd..84ccd3f 100644
--- a/frost-secp256k1/src/lib.rs
+++ b/frost-secp256k1/src/lib.rs
@@ -12,7 +12,7 @@ use k256::{
     AffinePoint, ProjectivePoint, Scalar,
 };
 use rand_core::{CryptoRng, RngCore};
-use sha2::{Digest, Sha256};
+use sha3::{Digest, Keccak256 as Sha256};

 use frost_core::frost;

@@ -20,7 +20,7 @@ use frost_core::frost;
 mod tests;

 // Re-exports in our public API
-pub use frost_core::{Ciphersuite, Field, FieldError, Group, GroupError};
+pub use frost_core::{Challenge, Ciphersuite, Field, FieldError, Group, GroupError};
 pub use rand_core;

 /// An error.
@@ -219,6 +219,28 @@ impl Ciphersuite for Secp256K1Sha256 {
             m,
         ))
     }
+
+    fn transform_r(R: ProjectivePoint) -> ProjectivePoint {
+        let uncompressed = R.to_affine().to_encoded_point(false);
+        let digest = sha3::Keccak256::digest(&uncompressed.as_bytes()[1..]);
+        let address: [u8; 20] = digest[12..].try_into().unwrap();
+        todo!()
+    }
+
+    /// Computes the challenge.
+    fn challenge(R: &ProjectivePoint, verifying_key: &ProjectivePoint, msg: &[u8]) -> Scalar {
+        use k256::elliptic_curve::point::AffineCoordinates;
+        let message_hash = sha3::Keccak256::digest(msg);
+        let public_key = verifying_key.to_affine();
+        let pubkey_x: [u8; 32] = public_key.x().into();
+        let pubkey_y_parity = public_key.y_is_odd().unwrap_u8();
+        let mut e_hasher = sha3::Keccak256::new();
+        e_hasher.update(pubkey_x);
+        e_hasher.update([pubkey_y_parity]);
+        e_hasher.update(message_hash);
+        //e_hasher.update(address);
+        Scalar::from_repr(e_hasher.finalize()).unwrap()
+    }
 }
```

**Comment by conradoplg** [comment]
Thanks for letting us know. This looks like an exciting use case of FROST!

However, we're wondering if this is something that you would like to be supported by this library or by the specification? We believe that wouldn't be possible since the specification is very close to be done and this particular library aims to just support that specification. We do encourage other people to build on top of it, though.

This use case can't be supported directly by our crates (`frost-core` to be precise). However,  `frost-core` does have an `internals` feature that, when enabled, exposes some lower-level functions (though we don't make promises of API stability for it). I think you can use it to write your own `sign()`  function which should be similar to the default `sign()` function but which computes and uses the customized challenge. Check the `frost-rerandomized` crate in this same repo for a similar example (in that case we need customized the binding factor computation and the public key that is input to the challenge).

**Comment by dvc94ch** [comment]
thanks, your pointers were very helpful. I'm still confused on one issue. Why does verifying the signature compute the public nonce as `z * G - pubkey * challenge` instead of `z * G + pubkey * challenge`?

**Comment by conradoplg** [comment]
> thanks, your pointers were very helpful. I'm still confused on one issue. Why does verifying the signature compute the public nonce as `z * G - pubkey * challenge` instead of `z * G + pubkey * challenge`?

That's unfortunately one aspect of Schnorr signatures that vary between implementations due to lack of standardization. There are two options:

- Compute the challenge response as `z = nonce + privkey * challenge`. Then when verifying it needs  `R = z * G - pubkey * challenge` . This is what FROST does.
- Compute the challenge response as `z = nonce - privkey * challenge`. Then when verifying it needs `R = z * G + pubkey * challenge`. This is what the Chainlink blog post shows.

The math works out in both cases, so it's just a matter of preference

**Comment by dvc94ch** [comment]
the code for frost-evm is here: https://github.com/Analog-Labs/frost-evm
