### ISSUE TITLE
Note in Ristretto255 near PublicKeyPackage where we impl `derive_group_info()` for v05

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#47]

**Comment by dconnolly** [comment]
Make this note in frost-ristretto255

**Comment by conradoplg** [comment]
I'm trying to understand this - we don't seem to implement `derive_group_info()` at all, but I think we don't need to, at least in our examples where there is a trusted dealer:

The group public key is computed directly from the secret in `keygen_with_dealer` (instead of taking the first element of `vss_commitment`); and the participant public keys are computed directly from their shares (instead of computing from `vss_commitment`), which is OK for the dealer to do. If we wanted an example without a trusted dealer, then I think we'll need this.

Therefore not sure what do here - can we just close the ticket and leave it for a DKG epic? Or should we add a comment about this?

**Comment by conradoplg** [comment]
OK I **finally** get it, `derive_group_info()` is very similar to `vss_verify`. But I think we might want to use the info computed in it, so I created #108
