### ISSUE TITLE
Using FROST with DLCs (Discreet Log Contracts)

### ISSUE THREAD

**Issue by sosaucily** [ZcashFoundation/frost#593]
Hi, I would like to ask about the feasibility of using FROST, and specifically this library, with DLCs which are a cryptographic system that requires an additional parameter to be aggregated. In brief, DLCs require both a nonce (R value) and public key to be to be pre-committed and used for aggregation. 

There is quite some development around DLCs, and supporting the features of FROST would be a great improvement. I wonder if there are any ideas from the community around the best way to implement such support? Or is there interest to get a PR into this repository for DLC support?

-----

Problem: Discreet Log Contracts are Bitcoin cryptographic systems which require oracles to pre-commit to their public key AND their Schnorr signature R values, but IIUC this aggregation isn't possible using FROST since FROST only allows for public key commitment while (aggregate) nonces are computed dynamically depending on the set of signers, and then additive secret sharing is used.

Background: A Discreet Log Contract (DLC) functions by having an "oracle" commit to generating a Schnorr signature in the future on some outcome in the "real world." This is done by having the oracle publish their public signing key, X, as well as the R value to be used on the future signature, and the possible messages it might sign. Given this information, parties can create blockchain transactions using 2-of-2 multisignatures and providing each other one-time verifiably encrypted signatures (aka adaptor signatures) of spending transactions, where the encryption key used is R + e*X (where e is the hash of the corresponding outcome). For more, see the original white-paper: https://adiabat.github.io/dlc.pdf and the open-source specification: https://github.com/discreetlogcontracts/dlcspecs.

Solution Proposal: If we wish to aggregate DLC oracles, polynomial secret sharing should be used on the signers' nonces just as it is used on their public signing keys. This would result in a static pre-determined R-value which the group of oracles could commit to at setup, as is required by the DLC protocol. This essentially amounts to implementing a more generic-looking MPC for schnorr signatures, as is described in the paper by Stinson and Strobl: https://link.springer.com/chapter/10.1007/3-540-47719-5_33.

Practically speaking, our hope would be to take an existing FROST implementation and re-use the aggregator/coordinator code as well as the key sharing implemented for the public signing keys for the nonces, since it seems to me that this would be a much more minimal piece of work than implementing from scratch.

Thanks!

**Comment by sosaucily** [comment]
I will close this request, as it's not getting feedback, and we are going to try and find a way to use FROST in a more similar fashion to the original specs

**Comment by chelseakomlo** [comment]
Thanks @sosaucily, and apologies for the delay, we were all away during the holiday period. 

I'm a bit puzzled by the requirements for DLCs, because in general, the R value for Schnorr should not be static, it has to be randomly generated for security to hold. Further, the message is generally determined before the final R value is fixed. This is also the case for the Stinson/Strobl protocol. Note that Stinson/Strobl is not secure in the preprocessing setting where muliple R values can be published before the message is committed to. 

There are deterministic multi-party Schnorr schemes (see Musig-DN, for example), but the R value is known only after all parties generate their contributions respectively, and the message is given as an input to the first round of signing. 

It would be helpful to have a sketch of what the ideal protocol is, without thinking about the specifics of which scheme can instantiate it; happy to think through ways to achieve it, whether that is FROST or some other scheme.
